# Generated by Django 5.2.4 on 2025-07-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_created_at_alter_todo_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
